name: Cethleann .NET Core
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Create Build Directory
      run: mkdir -p $GITHUB_WORKSPACE/Build/CethleannStandalone $GITHUB_WORKSPACE/Build/Cethleann
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build Independent Release
      run: dotnet publish --configuration Release --self-contained -r win10-x64 -o $GITHUB_WORKSPACE/Build/CethleannStandalone
    - name: Publish Independent Release
      uses: actions/upload-artifact@v1
      with:
        name: Cethleann-Standalone
        path: Build/CethleannStandalone
